# Generated by Django 3.0.5 on 2020-05-02 10:01

from django.db import migrations
from django.conf import settings

FLATPAGES = [
    {
        'title': 'About',
        'url': '/about/',
        'content': '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. '
                   'Praesent libero. Sed cursus ante dapibus diam. Sed nisi. '
                   'Nulla quis sem at nibh elementum imperdiet.'
                   'Duis sagittis ipsum. '
                   'Praesent mauris. Fusce nec tellus sed augue semper porta. '
                   '<b>Lorem ipsum dolor sit amet, consectetur adipiscing elit</b>. '
                   'Mauris massa. Vestibulum lacinia arcu eget nulla. '
                   'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>'

    },
    {
        'title': 'How we work',
        'url': '/how/',
        'content': '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. '
                   'Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis '
                   'ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia '
                   'arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos '
                   'himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. </p> '
    },
    {
        'title': 'Our Mission',
        'url': '/mission/',
        'content': '<p>Curabitur tortor. Pellentesque nibh. <b>Fusce nec tellus sed augue semper porta</b>. Aenean '
                   'quam. In scelerisque sem at dolor. <i>Lorem ipsum dolor sit amet, consectetur adipiscing '
                   'elit</i>. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas '
                   'porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis '
                   'quis ligula lacinia aliquet. Mauris ipsum. <i>Lorem ipsum dolor sit amet, consectetur adipiscing '
                   'elit</i>. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. </p> '
    }
]


def add_flatpages_data(apps, schema_editor):
    FlatePage = apps.get_model('flatpages', 'FlatPage')
    Site = apps.get_model('sites', 'Site')
    current_site = Site.objects.get(
        pk=getattr(settings, 'SITE_ID', 1)
    )
    for page in FLATPAGES:
        new_page = FlatePage.objects.create(
            title=page['title'],
            url=page['url'],
            content=page['content'],
        )
        new_page.sites.add(current_site)


def delete_flatpages_data(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    for page in FLATPAGES:
        page_object = FlatPage.objects.get(
            title=page['title'],
            url=page['url'],
            content=page['content']
        )
        page_object.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_site_data'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_flatpages_data,
            delete_flatpages_data
        ),
    ]
