# Generated by Django 3.0.5 on 2020-04-21 08:59
from datetime import date

from django.db import migrations

STARTUPS = [
    {
        'name': 'Arachnobots',
        'slug': 'arachnobots',
        'contact': 'contact@arachnobots.com',
        'description':
            'Remote-controlled internet-enabled'
            'spider robots',
        'founded_date': date(2014, 10, 31),
        'tags': ['mobile', 'augmented-reality'],
        'website':
            'https://frightenyourroomate.com'
    },
    {
        'name': 'Pod Point',
        'slug': 'pod-point',
        'contact': 'contact@pod-point.com',
        'description':
            'Remote-controlled internet-enabled'
            'internet of things',
        'founded_date': date(2009, 10, 31),
        'tags': ['mobile', 'django'],
        'website':
            'https://frighteneveryone.com'
    },
{
        'name': 'DevTeams',
        'slug': 'devteams',
        'contact': 'contact@devteams.com',
        'description':
            'Remote-controlled internet-enabled'
            'internet of things',
        'founded_date': date(2019, 10, 31),
        'tags': ['mobile', 'django'],
        'website':
            'https://devteams.co.uk'
    },


]


def add_startup_data(apps, schema_editor):
    Startup = apps.get_model('organizers', 'Startup')
    Tag = apps.get_model('organizers', 'Tag')
    for startup in STARTUPS:
        startup_object = Startup.objects.create(
            name=startup['name'],
            slug=startup['slug'],
            contact=startup['contact'],
            description=startup['description'],
            founded_date=startup['founded_date'],
            website=startup['website']
        )
        for tag_slug in startup['tags']:
            startup_object.tags.add(
                Tag.objects.get(slug=tag_slug)
            )


def delete_startup_data(apps, schema_editor):
    Startup = apps.get_model('organizers', 'Startup')
    for startup in STARTUPS:
        startup_object = Startup.objects.get(slug=startup['slug'])
        startup_object.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('organizers', '0002_tag_data'),
    ]

    operations = [
        migrations.RunPython(
            add_startup_data,
            delete_startup_data
        )
    ]
