# Generated by Django 3.0.5 on 2020-04-28 11:01
from datetime import date
from django.db import migrations

NEWSLINKS = [
    {
        'title': 'News Link 1',
        'pub_date': date(2014, 9, 3),
        'link': 'https://newlink1.com',
        'startup': 'arachnobots'
    },
    {
        'title': 'News Link 2',
        'pub_date': date(2017, 5, 23),
        'link': 'https://en.wikipedia.org/wiki/William_Shakespeare',
        'startup': 'jambon-software'
    },
    {
        'title': 'News Link 3',
        'pub_date': date(2008, 7, 21),
        'link': 'https://en.wikipedia.org/wiki/Monkey',
        'startup': 'pod-point'
    }
]


def add_newslink_data(apps, schema_editor):
    NewsLink = apps.get_model('organizers', 'NewsLink')
    Startup = apps.get_model('organizers', 'Startup')
    for newslink in NEWSLINKS:
        newslink_object = NewsLink.objects.create(
            title=newslink['title'],
            pub_date=newslink['pub_date'],
            link=newslink['link'],
            startup=Startup.objects.get(slug=newslink['startup'])
        )


def remove_newslink_data(apps, schema_editor):
    NewsLink = apps.get_model('organizers', 'NewsLink')
    Startup = apps.get_model('organizers', 'Startup')
    for newslink in NEWSLINKS:
        newslink_object = newslink.objects.get(
            title=newslink['title'],
            pub_date=newslink['pub_date'],
            link=newslink['link'],
            startup=Startup.objects.get(slug=newslink['startup'])
        )
        newslink_object.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('organizers', '0003_startup_data'),
    ]

    operations = [
        migrations.RunPython(
            add_newslink_data,
            remove_newslink_data
        )
    ]
