# Generated by Django 3.0.5 on 2020-04-28 11:41

from django.db import migrations, models
from django.utils.text import slugify

SLUG_LENGTH = 63


def add_slug_data(apps, schema_editor):
    NewsLink = apps.get_model('organizers', 'NewsLink')
    query = NewsLink.objects.all()
    for newslink in query:
        expected_slug = slugify(newslink.title)
        # Check if a startup with similar newslink exits and how many
        rivals = (
            NewsLink.objects.filter(
                startup=newslink.startup,
                slug__startswith=expected_slug
            ).count()
        )
        if rivals > 0:
            # Identify if rivals is 2 digit or 1
            str_len = (
                SLUG_LENGTH - len(str(rivals))
            )
            newslink.slug = '{}-{}'.format(
                expected_slug[:str_len-1],
                rivals + 1
            )
        else:
            newslink.slug = expected_slug
            newslink.save()

def remove_slug_data(apps, shema_editor):
    NewsLink = apps.get_model('organizers', 'NewsLink')
    NewsLink.objects.update(slug='')


class Migration(migrations.Migration):
    dependencies = [
        ('organizers', '0004_newslink_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslink',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH,
                default=''
            ),
        ),
        migrations.RunPython(
            add_slug_data,
            reverse_code=remove_slug_data
        ),
        migrations.AlterField(
            model_name='newslink',
            name='slug',
            field=models.SlugField(max_length=SLUG_LENGTH),
        ),

    ]
