# Generated by Django 3.0.5 on 2020-04-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_newslink_slug'),
    ]

    operations = [
    ]
