# Generated by Django 3.0.5 on 2020-04-21 09:41

from django.db import migrations

POSTS = [
    {
        'title': 'Test Post 1',
        'slug': 'test-post-1',
        'text':
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et '
            'dolore magna aliqua. Faucibus turpis in eu mi bibendum neque. Amet nisl purus in mollis. Pulvinar neque '
            'laoreet suspendisse interdum consectetur libero id faucibus nisl. Ullamcorper sit amet risus nullam '
            'eget. Facilisi cras fermentum odio eu feugiat. Non nisi est sit amet facilisis magna etiam tempor. '
            'Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Aliquam nulla facilisi cras '
            'fermentum odio. Elementum facilisis leo vel fringilla. Nec dui nunc mattis enim ut tellus. In eu mi '
            'bibendum neque egestas congue quisque egestas diam. Ut etiam sit amet nisl purus in mollis. Morbi '
            'tristique senectus et netus et malesuada fames.',
        'tags': ['augmented-reality', 'jenkins-pipeline', 'devops-culture'],
        'startups': ['arachnobots', 'pod-point']

    },
    {
        'title': 'Test Post 2',
        'slug': 'test-post-2',
        'text':
            'Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Odio aenean sed adipiscing '
            'diam donec adipiscing tristique. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Molestie a '
            'iaculis at erat pellentesque adipiscing commodo elit at. Ultrices in iaculis nunc sed augue lacus '
            'viverra. Iaculis at erat pellentesque adipiscing commodo elit at. Neque ornare aenean euismod elementum '
            'nisi quis eleifend quam adipiscing. Odio eu feugiat pretium nibh ipsum consequat. Cras semper auctor '
            'neque vitae. Egestas dui id ornare arcu odio ut sem nulla. Scelerisque viverra mauris in aliquam. Amet '
            'nulla facilisi morbi tempus iaculis urna id volutpat lacus. Mi quis hendrerit dolor magna eget est '
            'lorem. Odio facilisis mauris sit amet massa vitae tortor condimentum. Diam phasellus vestibulum lorem '
            'sed risus. ',
        'tags': ['augmented-reality', 'jenkins-pipeline'],
        'startups': ['arachnobots']
    },
    {
        'title': 'Test Post 3',
        'slug': 'test-post-3',
        'text':
            'Viverra justo nec ultrices dui sapien eget mi. Eu ultrices vitae auctor eu augue. Vulputate mi sit amet '
            'mauris commodo quis imperdiet massa. Ullamcorper eget nulla facilisi etiam dignissim. Volutpat odio '
            'facilisis mauris sit. Sem integer vitae justo eget magna fermentum. Dui sapien eget mi proin sed libero '
            'enim sed. Donec ultrices tincidunt arcu non. Pellentesque massa placerat duis ultricies. Pulvinar '
            'elementum integer enim neque volutpat ac. Ut placerat orci nulla pellentesque dignissim enim sit amet '
            'venenatis. Egestas maecenas pharetra convallis posuere morbi leo urna. Hac habitasse platea dictumst '
            'vestibulum. Aliquam sem fringilla ut morbi tincidunt augue interdum. Sed vulputate odio ut enim blandit '
            'volutpat maecenas. Enim nec dui nunc mattis enim ut tellus elementum. Porttitor eget dolor morbi non '
            'arcu risus quis varius quam. Congue eu consequat ac felis donec et odio pellentesque. ',
        'tags': ['jenkins-pipeline', 'devops-culture'],
        'startups': ['pod-point']
    }
]


def add_post_data(apps, schema_editor):
    Post = apps.get_model('blogs', 'Post')
    Tag = apps.get_model('organizers', 'Tag')
    Startup = apps.get_model('organizers', 'Startup')
    for post in POSTS:
        post_object = Post.objects.create(
            title=post['title'],
            slug=post['slug'],
            text=post['text']
        )
        for tag_slug in post['tags']:
            post_object.tags.add(
                Tag.objects.get(slug=tag_slug)
            )
        for startup_slug in post['startups']:
            post_object.startups.add(
                Startup.objects.get(slug=startup_slug)
            )


def delete_post_data(apps, schema_editor):
    Post = apps.get_model('blogs', 'Post')
    for post in POSTS:
        post_object = Post.objects.get(slug=post['slug'])
        post_object.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0001_initial'),
        ('organizers', '0003_startup_data.py'),
    ]

    operations = [
    ]
