# Generated by Django 3.0.5 on 2020-06-05 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0003_auto_20200428_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'],
                     'permissions': (('view_future_post', 'Can view unpublished Post'),), 'verbose_name': 'blog post'},
        ),
    ]
