# Generated by Django 3.0.5 on 2020-08-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_data'),
        ('blogs', '0005_posts_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='users.User'),
            preserve_default=False,
        ),
    ]
