# Generated by Django 3.1.1 on 2020-09-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_post_author'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together={('slug', 'pub_date')},
        ),
    ]
